---
version: 2
multicolumn: false
web-width: 400px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/polutions/contCDMX.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/3629/articles/438014/master/folder/figures/polutions"
    url: "/users/3629/articles/438014/master/file/figures/polutions/contCDMX.png"
