---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/WhatsApp Image 2020-05-07 at 11-57-05 PM/UVI-OMI.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/3629/articles/438014/master/folder/figures/WhatsApp Image
      2020-05-07 at 11-57-05 PM"
    url: "/users/3629/articles/438014/master/file/figures/WhatsApp%20Image%202020-05-07%20at%2011-57-05%20PM/UVI-OMI.png"
