---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/tabla/tabla.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/3629/articles/438014/master/file/figures/tabla/tabla.html"
